### PR TITLE
PLANET-5363 Revert "PLANET-4536: Perf: Reduce unused dependencies from bootstrap in code"

### PR DESCRIPTION
**Pull request by Inwerpsel**
Reverts greenpeace/planet4-master-theme#1116

Ref: https://jira.greenpeace.org/browse/PLANET-5363
Ref reverted ticket: https://jira.greenpeace.org/browse/PLANET-4536

### CODE REVIEW

**Comment by comzeradd** [comment]
Not sure if we want to bring back everything. Mostly concerned about things that might have changed in our css code in the meantime. For the collapsible elements the relevant code seems to be in `_cards.scss` and `_transitions.scss` (I don't see the first one on the list, but [here it is](https://github.com/twbs/bootstrap/blob/main/scss/_card.scss)).

@pablocubico thoughts?

**Comment by Inwerpsel** [comment]
@comzeradd Indeed, probably best to start by re-adding these parts we currently know are missing, which should be pretty safe. Maybe we can follow it up with a ticket to check if there are other parts we need to add again. For example if we missed usages in the content or in child themes that depend on it.

**Comment by Inwerpsel** [comment]
Made a PR to add only `_cards.scss` and `_transitions.scss` https://github.com/greenpeace/planet4-master-theme/pull/1179, which solves the currently known issues. I'll close this one for now.

**Comment by pablocubico** [comment]
@comzeradd Agreed, I think only `_transitions` is needed for the accordion, but we chatted about this with Pieter, I remembered those were re-added for the Bulgaria site, so I guess let's go ahead and add both `cards` and `transitions`.

**Pull request closed without merging**
