### PR TITLE
PLANET-3744 - Hide CTA links from page header on admin

### PR DESCRIPTION
**Pull request by comzeradd**
Ref: https://jira.greenpeace.org/browse/PLANET-3744

This is a small counterpart for greenpeace/planet4-plugin-blocks#599

### CODE REVIEW

**Comment by kirdia** [comment]
I see it could be done in cmb2 settings also, could a little bit more clear in php

https://github.com/CMB2/CMB2/wiki/Field-Parameters#show_on_cb

**Comment by sagarsdeshmukh** [comment]
@comzeradd - Please add resource version [here](https://github.com/greenpeace/planet4-master-theme/blob/develop/classes/class-p4-post-campaign.php#L385), so that it load the updated css .

Also better we will add hint for web editor on backend about "On Campaigns the CTA buttons are hidden" or the CMB2 field callback function to hide the field conditionally. 
(Example - https://github.com/greenpeace/planet4-master-theme/blob/develop/classes/class-p4-metabox-register.php#L409 , https://github.com/greenpeace/planet4-master-theme/blob/develop/admin/js/cmb2_form_validation.js#L36)

**Comment by comzeradd** [comment]
I see that `campaign.css` gets a version number. Currently `5.2.2` on stage, but not sure where this comes from.

The cmb2 callback filter seems indeed more clean solution. I tried it out, but I couldn't make it work. Regardless what the callback returns the fields are always visible. Any help would be appreciated.

**Comment by kirdia** [comment]
Ammended the commit to do the post type check where cmb2 fields are registered.

**Comment by sagarsdeshmukh** [comment]
@kirdia - I tested the call back function fix on local, It works just perfect 💯 . well done 👍 
Just small thing could you please also remove the `New Tab` field as well -
image

**Comment by kirdia** [comment]
I tried to add it that too, but now all of them are shown.
I don't know why it is inconsistent.
Do we change the visibility in other place also?
Can you retry creating a new campaign post?

**Comment by sagarsdeshmukh** [comment]
@kirdia - The latest changes working fine on my local.
image

**Comment by kirdia** [comment]
Yeap, it was the function's visibility on my local indeed.
Thanx for checking.

**Pull request merged**
