### PR TITLE
Changed the temp dir path with system temp dir

### PR DESCRIPTION
**Pull request by sagarsdeshmukh**

### CODE REVIEW

**Comment by angtheod** [comment]
Circleci test failed
`Fatal error: require(): Failed opening required '/home/circleci/project/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /home/circleci/project/tests/bootstrap.php on line 57`

**Comment by angtheod** [comment]
Actually , this is caused due to this change [here](https://github.com/greenpeace/planet4-master-theme/commit/05a5f4ecd6b10d19007b902db7ea85e461046eb3#diff-10eafd8bf5fbdde867b86fe38d30b9bbR57)
There is no composer autoloader for the master-theme repo.

**Comment by angtheod** [comment]
@sagarsdeshmukh could you remove this change and try the tests again?

**Comment by angtheod** [comment]
`Fatal error: Trait 'SteveGrunwell\PHPUnit_Markup_Assertions\MarkupAssertionsTrait' not found in /home/circleci/project/tests/test-category-page.php on line 14`

I am guessing these issues have to do with this [PR](https://github.com/greenpeace/planet4-master-theme/pull/674) not being merged yet.
@comzeradd What you think?

**Comment by comzeradd** [comment]
Yes, I guess we can ignore for now until the circleci configuration is fixed.

This change also breaks Travis. If it's a quick fix please do fix it. Otherwise don't bother, since we are going to remove Travis once CircleCI works properly.

**Comment by kirdia** [comment]
> `Fatal error: Trait 'SteveGrunwell\PHPUnit_Markup_Assertions\MarkupAssertionsTrait' not found in /home/circleci/project/tests/test-category-page.php on line 14`
> 
> I am guessing these issues have to do with this [PR](https://github.com/greenpeace/planet4-master-theme/pull/674) not being merged yet.
> @comzeradd What you think?

No, this has to do with this change.
The tests need the dev dependencies (actually this one, stevegrunwell/phpunit-markup-assertions) and timber lib to work.

**Comment by kirdia** [comment]
Closing this in favor of #674. Changes made there so that the unit tests can run in ci and locally.

**Pull request closed without merging**
