### PR TITLE
Fix Carousel Header layout

### PR DESCRIPTION
**Pull request by GP-Dan-Tovbein**
In preparation of #2188 we need to split fixes and improvents in small PRs, and then easy to review and merge.

# About the issue
Is not currently possible to click on controls. That's why the related spec is failing.

### CODE REVIEW

**Review by mleray — COMMENTED** [review]
@GP-Dan-Tovbein can you please clarify what the issue is? Because I'm testing on the [Gutenberg instance homepage](https://www-dev.greenpeace.org/gutenberg/) and I can use the indicators just fine 🤔

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pluto](https://www-dev.greenpeace.org/test-pluto) | [admin](https://www-dev.greenpeace.org/test-pluto/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pluto/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pluto) | [composer-local.json](https://github.com/greenpeace/planet4-test-pluto/blob/main/composer-local.json)

:watch: 2024.10.21 19:17:19

**Review by mardelnet — COMMENTED** [review]
Hey @GP-Dan-Tovbein 
I don't completely understand how changing the `pointer-events` property can fix/affect the carousel buttons. 
If the problem is the buttons cannot be clicked, shouldn't we use for the overlay a `z-index smaller than the buttons', instead?

**Comment by GP-Dan-Tovbein** [comment]
> Hey @GP-Dan-Tovbein I don't completely understand how changing the `pointer-events` property can fix/affect the carousel buttons. If the problem is the buttons cannot be clicked, shouldn't we use for the overlay a `z-index` smaller than the buttons', instead?

The reason is that there is an overlay which is on top of buttons and the buttons cannot be clicked. So, disabling any pointer events to overlay will fix the issue. Regarding `z-index`, is not always a good practice honestly.

**Review by mardelnet — APPROVED** [review]

**Pull request merged**
