### PR TITLE
Removed semicolons and vars in JS

### PR DESCRIPTION
**Pull request by 45kb**
Just hope it's of help.

### CODE REVIEW

**Comment by comzeradd** [comment]
Thanks @45kb. Can you elaborate a bit on these changes? In general it's a good practice to use semicolon on js code and it's common on most coding style guides.

I'm also using Atom. Atom should read `.editorconfig` for indentation.

**Comment by 45kb** [comment]
Hi @comzeradd the point is Javascript do the semicolon insertion by itself when files are parsed so nowadays almost nobody use them, i was reading at http://inimino.org/~inimino/blog/javascript_semicolons and looks to me in this case may be not necessary, i did it to cut down more chars from your files if you feel more comfortable reading with the semicolons (which is understandable) you can leave them you know :)

Let me try see what happened with indentation, sorry about that.

**Comment by angtheod** [comment]
Hello @45kb in any case we are merging into develop (not directly into master)

**Comment by comzeradd** [comment]
> Hi @comzeradd the point is Javascript do the semicolon insertion by itself when files are parsed so nowadays almost nobody use them

Indeed, semicolons are optional but most projects still use them as a good practice to make the code more readable. We also try to be as close as possible to Wordpress coding standards, that in this case [suggests](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/#semicolons) to always use semicolons.

I'll close this for now, but feel free to work on other issues. For Atom, installing [editorconfig](https://atom.io/packages/editorconfig) and various linter packages should help with the code styling.

**Comment by 45kb** [comment]
Thanks @comzeradd @angtheod yes it's understandable at all.

**Comment by angtheod** [comment]
Np, thank you too for your effort @45kb

**Pull request closed without merging**
