### PR TITLE
PLANET-6455 Add filter to catch core bug removing gradients

### PR DESCRIPTION
**Pull request by Inwerpsel**
* Core did not take the case into account where a background-image is
not only a gradient. As a result gradient + URL combination gets
stripped out.
* Workaround: add filter that checks the remainder of the
$css_test_string. This string is progressively dismantled with stuff
they don't want to perform the check for certain characters on by WP
core. So if we remove a gradient from this and only a comma is left,
it's probably valid CSS.

Ref: https://jira.greenpeace.org/browse/PLANET-6455

TODO:
* ~~There still seems to be an issue with the scrolling script which I didn't have locally but is persistent on the test instance. We can merge this PR already but that issue might need to be fixed to fully use it as a reusable block.~~ It was just in the other repo, so created a PR there as well to address that https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/708/files

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pluto](https://www-dev.greenpeace.org/test-pluto) | [admin](https://www-dev.greenpeace.org/test-pluto/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pluto/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pluto) | [composer-local.json](https://github.com/greenpeace/planet4-test-pluto/blob/main/composer-local.json)

:watch: 2021.11.02 16:47:18

**Comment by comzeradd** [comment]
Looks good. Just doing a final check locally.

Can you add the ticket prefix on commit messages for reference?

**Review by comzeradd — APPROVED** [review]
Works great 👍🏻 

Please add the ticket prefix in the commit messages (not just the PR title) before you merge.

**Comment by Inwerpsel** [comment]
> Works great 👍🏻
> 
> Please add the ticket prefix in the commit messages (not just the PR title) before you merge.

I added these to the commit message body with a link.

**Pull request merged**
