### PR TITLE
PLANET-3393: CPP - Review color swatch options for the customizer

### PR DESCRIPTION
**Pull request by pablocubico**
Ref: https://jira.greenpeace.org/browse/PLANET-3393

### CODE REVIEW

**Comment by comzeradd** [comment]
@pablocubico you may have some indentation issues. `phpcs` is complaining.

**Comment by comzeradd** [comment]
Just for [consistency](https://planet4.greenpeace.org/handbook/dev-git-best-practices/#context), can you put the `PLANET-xxxx` comment on the start of the commit messages? Also, no need to add a period at the end of the commit message.

**Comment by pablocubico** [comment]
> Just for [consistency](https://planet4.greenpeace.org/handbook/dev-git-best-practices/#context), can you put the `PLANET-xxxx` comment on the start of the commit messages? Also, no need to add a period at the end of the commit message.

Will do! In fact, I should squash these commits...

**Comment by pablocubico** [comment]
@comzeradd This one got a last minute update and it's ready to go.

**Comment by comzeradd** [comment]
@pablocubico can you do a last check on `phpcs`? It complains about some spacing issues.

**Comment by pablocubico** [comment]
@comzeradd done!

**Pull request merged**
