### PR TITLE
PLANET-7380 Drop Campaigns theme customizer

### PR DESCRIPTION
**Pull request by sagarsdeshmukh**
Ref. https://jira.greenpeace.org/browse/PLANET-7380

> Requirements
> This refers to all the options that are currently locate in the custom "Theme Options" sidebar that's only visible to Campaign pages.
> Completely remove the customization option of sections: Theme, Fonts, Footer.
> Clean/Delete relevant css, template code and fonts that are not need anymore from our code.
> We want to keep the "Navigation" section customization options. But ideally we want to move them in the main sidebar and use the same component we use in Actions.

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [iocaste](https://www-dev.greenpeace.org/test-iocaste) | [admin](https://www-dev.greenpeace.org/test-iocaste/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-iocaste/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-iocaste) | [composer-local.json](https://github.com/greenpeace/planet4-test-iocaste/blob/main/composer-local.json)

:watch: 2024.04.30 09:51:46

**Comment by comzeradd** [comment]
We should probably also drop the whole [themes](https://github.com/greenpeace/planet4-master-theme/tree/v1.286.0/themes) folder

**Review by mleray — COMMENTED** [review]
Should we also remove [these lines](https://github.com/greenpeace/planet4-master-theme/blob/4b3324a3bb7fcf1dc574cef5e6ff78305a1f0016/src/PostCampaign.php#L199-L204)? 🤔

**Comment by sagarsdeshmukh** [comment]
> Should we also remove [these lines](https://github.com/greenpeace/planet4-master-theme/blob/4b3324a3bb7fcf1dc574cef5e6ff78305a1f0016/src/PostCampaign.php#L199-L204)? 🤔

Yes, good catch 👍  I updated the PR.

**Review by mleray — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
