### PR TITLE
PLANET-5708: PDF icon wrong color in secondary CTA buttons

### PR DESCRIPTION
**Pull request by pablocubico**
Ref: https://jira.greenpeace.org/browse/PLANET-5708

See styleguide PR: https://github.com/greenpeace/planet4-styleguide/pull/86

Pin Styleguide for PDF icons in secondary buttons colors

### CODE REVIEW

**Review by Inwerpsel — COMMENTED** [review]
Left a small comment on the styleguide commit https://github.com/greenpeace/planet4-styleguide/commit/b739dc751e8c26b22838637295660ced94afdf70#r44948328

**Comment by comzeradd** [comment]
If the styleguide PR is merged, then a CI pipeline is triggered to bump the other two repos. So no need to manually bump the styleguide here. Maybe it's better to open the PR on the styleguide, so the review can take place there.

**Comment by pablocubico** [comment]
@comzeradd ah, good point! I did create a PR, forgot to link it here.

**Comment by pablocubico** [comment]
> If the styleguide PR is merged, then a CI pipeline is triggered to bump the other two repos. So no need to manually bump the styleguide here. Maybe it's better to open the PR on the styleguide, so the review can take place there.

Ah no, it looks like it was never created, I just added it: https://github.com/greenpeace/planet4-styleguide/pull/86

**Comment by comzeradd** [comment]
Approved the [pipeline](https://app.circleci.com/pipelines/github/greenpeace/planet4-styleguide/483/workflows/e732cf17-6105-42bc-b0ac-68e941d51b27), so the styleguide changes auto-committed to both repos.

**Pull request closed without merging**
