### PR TITLE
Fix Sitemap links

### PR DESCRIPTION
**Pull request by lithrel**
Ref: https://jira.greenpeace.org/browse/PLANET-6793
Following: https://github.com/greenpeace/planet4-master-theme/pull/2085

- fix post links
- fix category links
- move up empty condition to avoid empty category
- fix font-family for list content

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pandora](https://www-dev.greenpeace.org/test-pandora) | [admin](https://www-dev.greenpeace.org/test-pandora/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pandora/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora) | [composer-local.json](https://github.com/greenpeace/planet4-test-pandora/blob/main/composer-local.json)

:watch: 2023.08.30 11:27:00

**Comment by comzeradd** [comment]
Looking at the previous PR and it seems to enable the new Sitemap when [new visual identity is enabled](https://github.com/greenpeace/planet4-master-theme/blob/6c1e1b08120efdccd88b7cf0d7b3dd16ce6094f4/page-templates/sitemap.php#L24). That shouldn't be the case. It should be enabled when new IA is activated.

**Comment by lithrel** [comment]
> Looking at the previous PR and it seems to enable the new Sitemap when [new visual identity is enabled](https://github.com/greenpeace/planet4-master-theme/blob/6c1e1b08120efdccd88b7cf0d7b3dd16ce6094f4/page-templates/sitemap.php#L24). That shouldn't be the case. It should be enabled when new IA is activated.

Ah my bad, I mixed up the two states; fixed :ok:

**Review by comzeradd — APPROVED** [review]
👍🏻

**Pull request merged**
