### PR TITLE
PLANET-5232 Add a visited state to blue links

### PR DESCRIPTION
**Pull request by dpivo**
Added a function that cycles through a tags on a page and adds a class if the link color is blue. That class contains the :visited styles

### CODE REVIEW

**Comment by comzeradd** [comment]
Why not do this in css? The "blue links" are the ones using `$link-color` and it seems we only use that [in a couple of places](https://github.com/greenpeace/planet4-styleguide/search?q=link-color&unscoped_q=link-color). We could add a `$link-color-visited` variable and adjust the css code.

**Comment by mleray** [comment]
> in a couple of places

**Comment by mleray** [comment]
> Why not do this in css? The "blue links" are the ones using `$link-color` and it seems we only use that [in a couple of places](https://github.com/greenpeace/planet4-styleguide/search?q=link-color&unscoped_q=link-color). We could add a `$link-color-visited` variable and adjust the css code.

Made a mess with the PR, sorry 🤦 Anyway, at first it was using css but the `$link-color` is set in `src/base/_typography.scss` and other links (for example buttons) don't have a `:visited` state, they were picking up the changes too and we don't want that to happen... So in css we would either need a really long selector (i.e. `:not(.btn)` etc) or we would need to override the `:visited` selector for all of them. With the risk of course to forget some of them, or to forget to add this selector in case we add new links :/

**Comment by comzeradd** [comment]
Yes, good point. I left a comment in the ticket for Will to review. This seems like a hack to me. If we want visited color state we should code one for all of our link variations and classes (which is a good practice anyway).

**Comment by comzeradd** [comment]
Per latest ticket comment, we are not doing this after all.

**Pull request closed without merging**
