### PR TITLE
PLANET-1868 - Make 4 column blocks responsive

### PR DESCRIPTION
**Pull request by comzeradd**
Required for greenpeace/planet4-plugin-blocks#243

### CODE REVIEW

**Comment by kirdia** [comment]
@nikos are we removing slick from the 4 column block? Removing this will not apply slick to the first row of this block.
You can slickify method to apply slick to this row also.

**Comment by ashish173** [comment]
I am not sure if I fully understand why we are removing this file to ensure responsiveness.

**Comment by comzeradd** [comment]
This script adds inline fixed widths to these columns and also breaks the flex grid. So for instance, if we have only 3 publications these won't expand to cover full width of the page.

I can tweak it to only run this script when we have at least 4 elements. I did some local tests without the script and the "load more" functionality seems to work the same. I'll do another run locally with the proposed tweak.

**Comment by comzeradd** [comment]
I amended the commit so we don't apply the slick code only when we have less than 4 publications. It's when we actually need a more responsive design.

**Comment by kirdia** [comment]
@comzeradd I think slick js was added to provide swiping functionality on smaller screen sizes.
 If functionality is not affected in case we have less than 4 publications, then it is fine :+1:

**Comment by comzeradd** [comment]
Yes, good point. Since we know the breakpoint for this I made a small change just to be sure we don't break slick functionality on small screen sizes. I think it's good to go now.

**Pull request merged**
