### PR TITLE
Add new placeholder images

### PR DESCRIPTION
**Pull request by GP-Dan-Tovbein**
As a requirement of [PLANET-6704](https://jira.greenpeace.org/secure/RapidBoard.jspa?rapidView=78&projectKey=PLANET&view=detail&selectedIssue=PLANET-6704), we need to add a couple of images used as placeholders through the `core/media-text`

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [sinope](https://www-dev.greenpeace.org/test-sinope) | [admin](https://www-dev.greenpeace.org/test-sinope/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-sinope/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-sinope) | [composer-local.json](https://github.com/greenpeace/planet4-test-sinope/blob/main/composer-local.json)

:watch: 2022.05.10 19:45:50

**Review by mleray — APPROVED** [review]
Maybe good to avoid special characters/spaces in files' names? I'm thinking of `placeholder-546×415.jpg` which seems to use a different cross symbol than the others, not sure if that might cause issues.
Apart from that looks good to me 👍

**Review by comzeradd — CHANGES_REQUESTED** [review]
These should be inside `/images/`, because `assets/src/` is excluded from deployment builds.

**Review by comzeradd — APPROVED** [review]
I did the changes to unblock the other PR

**Pull request merged**
