### PR TITLE
Test deleting previous comment

### PR DESCRIPTION
**Pull request by Inwerpsel**
Just for testing https://github.com/greenpeace/planet4-circleci/pull/49

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [nix](https://www-dev.greenpeace.org/test-nix)

:watch: 2021.04.30 16:00:04

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [nix](https://www-dev.greenpeace.org/test-nix)

:watch: 2021.04.30 16:01:40

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [nix](https://www-dev.greenpeace.org/test-nix)

:watch: 2021.04.30 16:03:43

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [nix](https://www-dev.greenpeace.org/test-nix)

:watch: 2021.04.30 16:11:43

**Comment by Inwerpsel** [comment]
https://github.com/greenpeace/planet4-circleci/pull/49#issuecomment-1003958058

**Pull request closed without merging**
