### PR TITLE
PLANET-6646 Write an e2e test for the navigation bar

### PR DESCRIPTION
**Pull request by mleray**
### Description

See [PLANET-6646](https://jira.greenpeace.org/browse/PLANET-6646)

### Testing

On local you can run the new test via `npx playwright test tests/e2e/navigation-bar.spec.js` or using VSCode

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [iocaste](https://www-dev.greenpeace.org/test-iocaste) | [admin](https://www-dev.greenpeace.org/test-iocaste/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-iocaste/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-iocaste) | [composer-local.json](https://github.com/greenpeace/planet4-test-iocaste/blob/main/composer-local.json)

:watch: 2023.07.27 09:42:55

**Review by lithrel — APPROVED** [review]
:+1:

**Comment by mleray** [comment]
@lithrel please have another look, I rewrote the test to create a new page so it should work in all cases now!

**Review by lithrel — APPROVED** [review]
:+1:

**Pull request merged**
