### PR TITLE
PLANET-5441 apply url_encode to twitter text

### PR DESCRIPTION
**Pull request by lovlin-thakkar**
For https://github.com/greenpeace/planet4/issues/109

url_encode method should convert # to %23
https://twig.symfony.com/doc/3.x/filters/url_encode.html

It would convert the link from [bad link](https://twitter.com/share?url=https://www.greenpeace.org/canada/en/story/41373/why-you-have-to-say-gnlnonmerci-before-september-14/&text=WHY%20YOU%20HAVE%20TO%20SAY%20GNLNonMerci%20BEFORE%20SEPTEMBER%2014%20!%20via%20@GreenpeaceCA&related=GreenpeaceCA) to [correct link](https://twitter.com/intent/tweet?url=https%3A%2F%2Fwww.greenpeace.org%2Fcanada%2Fen%2Fstory%2F41373%2Fwhy-you-have-to-say-gnlnonmerci-before-september-14%2F&text=WHY%20YOU%20HAVE%20TO%20SAY%20%23GNLNonMerci%20BEFORE%20SEPTEMBER%2014%20!%20via%20%40GreenpeaceCA&related=GreenpeaceCA)

### CODE REVIEW

**Comment by sagarsdeshmukh** [comment]
Hi @lovlin-thakkar ,

Thank you for the PR :)

Below are the small comments from my side, other than that PR looks good to me 👍 
- Could you rename the commit message with ticket number as a prefix (eg. PLANET-5441 <commit message> )
- We need to apply similar fix for share on [email button](https://github.com/greenpeace/planet4-master-theme/blob/master/templates/blocks/share_buttons.twig#L24) and open graph fields at [here](https://github.com/greenpeace/planet4-master-theme/blob/master/templates/blocks/meta_fields.twig#L45).

**Comment by lovlin-thakkar** [comment]
Hi, I have made the changes. BTW, @comzeradd can you or anyone add the "hacktoberfest-accepted" label to the PR? This would help count this contribution towards [hacktoberfest](https://hacktoberfest.digitalocean.com)!

**Comment by comzeradd** [comment]
Thank you very much with the contribution :green_heart: 

Are you familiar with squashing the commits into one? We can also do it, but then maybe the PR doesn't count in Hacktorberfest metrics.

Since you have 5 commits and we want to squash the all into one, the easiest way would be:
```
git reset --soft HEAD~5
git commit -m "PLANET-5441 Apply url_encode to twitter text"
git push -f origin master
```

**Comment by lovlin-thakkar** [comment]
@comzeradd I tried the commands you have pasted above. I think it is not working because your repo has moved significantly since I forked it.

**Comment by comzeradd** [comment]
Indeed. We'll merge #1218. Hopefully Hacktorberfest can detect your commit there too.

**Comment by comzeradd** [comment]
Thank you very much again @lovlin-thakkar. You commit was merged at #1218

**Pull request closed without merging**
