### PR TITLE
Planet 2561

### PR DESCRIPTION
**Pull request by onyekaa**
Master branch of all changes made for Planet 2561. Merged in the deploy branch.
Changes include:
- Exporter functionality
- The metaboxes for campaign theming
- The Campaign post type twig and php files.

### CODE REVIEW

**Comment by comzeradd** [comment]
This has similar issues with the plugin-blocks PR. It's full with fixup commits and merge commits from the target branch.

I see this is still WIP. But when it's ready to be merged, we should spend some time to clean up the commits.

**Comment by onyekaa** [comment]
@comzeradd I'm basically done with it. You want me to squash just the merge commits? Or which other ones?

**Comment by comzeradd** [comment]
The merge commits that were created as part of merging PRs to this branch are fine. The ones that shouldn't be there are ones that merge the target branch back into this. (eg. `Merge branch 'develop' into planet-2561`).

Additionally the PR has many fixup commits (eg. `Linter fixes`, `Formatting fixes`, etc). In general [we avoid](https://planet4.greenpeace.org/handbook/dev-git-best-practices/#amend) having commits that fix syntax, linting, typo errors that were introduced on previous commits of the same PR.

**Comment by kirdia** [comment]
Ideally these commits (to which Nikos is referring to) should not exist as they pollute the git history
For example these commits
commit 2d6d2ea108122077a69d5c2851e89e087b0b2c62
commit 0c72f6302c8a3390fe6da4aa49ddbbd63990d5f4
commit e61ffa5f7a502f578cd8e6c5d6da04667cc2ddc8 (pull/703)

As this is an evolving codebase, we need to keep the git history as clean as possible.
And while these commits have some value during the lifeline of the branch/feature development they don't have any value for us after the feature is completed and merged and makes it harder to maintain the code.

**Comment by comzeradd** [comment]
Closing this in favor of #751

**Pull request closed without merging**
