### PR TITLE
PLANET-7628: Add Articles block from the P4 plugin

### PR DESCRIPTION
**Pull request by mardelnet**
Ref: https://jira.greenpeace.org/browse/PLANET-7628

<hr>

**DESCRIPTION:** 
This PR adds to the master theme the Articles block code, which is extracted from the P4 plugin.

<hr>

**RELATED PR:**
https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1257

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pluto](https://www-dev.greenpeace.org/test-pluto) | [admin](https://www-dev.greenpeace.org/test-pluto/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pluto/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pluto) | [composer-local.json](https://github.com/greenpeace/planet4-test-pluto/blob/main/composer-local.json)

:watch: 2024.10.14 07:59:12

**Review by mleray — COMMENTED** [review]
If I deactivate the plugin on the test instance, it seems the `Manual Override` functionality doesn't work. I don't see the suggestions appear and if I press `Enter` nothing happens but then I can't update other block settings.

Screenshot 2024-10-14 at 12 50 52

**Comment by mardelnet** [comment]
> If I deactivate the plugin on the test instance, it seems the `Manual Override` functionality doesn't work. I don't see the suggestions appear and if I press `Enter` nothing happens but then I can't update other block settings.

Nice catch, @mleray 
Apparently, this issue is not directly connected with this PR since it also happens with other blocks that use the override functionality (such as the Covers) when the P4 plugin is disabled. However, I'll try to fix it here.

**Comment by mleray** [comment]
> Nice catch, @mleray Apparently, this issue is not directly connected with this PR since it also happens in other branches (`main`) with blocks that use the override functionality (such as the Covers) when the P4 plugin is disabled. However, I'll try to fix it here.

@mardelnet if it's a known bug that affects other blocks too, I'm also fine with fixing it in a separate PR, as you wish!

**Comment by mardelnet** [comment]
> @mardelnet if it's a known bug that affects other blocks too, I'm also fine with fixing it in a separate PR, as you wish!

Fixed!

**Comment by mleray** [comment]
It looks like now the `Related Articles in post` setting is no longer working (with or without the plugin), see [this post](https://www-dev.greenpeace.org/test-pluto/press/1113/duis-posuere-6/) for example

**Comment by mardelnet** [comment]
> It looks like now the `Related Articles in post` setting is no longer working (with or without the plugin), see [this post](https://www-dev.greenpeace.org/test-pluto/press/1113/duis-posuere-6/) for example

Can you re-check it, @mleray ?
I haven't changed anything, the problem seemed to be a mistake in the `composer-local.json` file.

**Review by mleray — APPROVED** [review]
Looks good to me 👏

**Pull request merged**
