### PR TITLE
PLANET-7638 Add e2e tests for GF redirect and page confirmation types

### PR DESCRIPTION
**Pull request by mleray**
### Description

See [PLANET-7638](https://jira.greenpeace.org/browse/PLANET-7638) & [PLANET-7639](https://jira.greenpeace.org/browse/PLANET-7639)

Until now we only had an e2e test for the text confirmation type.

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [jupiter](https://www-dev.greenpeace.org/test-jupiter) | [admin](https://www-dev.greenpeace.org/test-jupiter/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-jupiter/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-jupiter) | [composer-local.json](https://github.com/greenpeace/planet4-test-jupiter/blob/main/composer-local.json)

:watch: 2024.10.16 14:06:47

**Review by mardelnet — DISMISSED** [review]
LGTM @mleray 
I would suggest adding some `JSDocs`, especially to the functions in the `tests/e2e/tools/lib/gravity-forms.js` file to make it easier to maintain.

**Review by mardelnet — COMMENTED** [review]
I don't know if this could be a problem, but locally, the tests are creating new posts that are not deleted afterward. I don't see this happening in the dev instance.

Posts-‹-Greenpeace-—-WordPress

**Comment by mleray** [comment]
> I don't know if this could be a problem, but locally, the tests are creating new posts that are not deleted afterward. I don't see this happening in the dev instance.

@mardelnet this is expected, in the CI pipeline somewhere we have a command to remove after the tests all the posts that they created. It's not the case on local so we need to clean up ourselves 😬

**Comment by mleray** [comment]
@mardelnet I've added the test for the "page" confirmation type in this PR as well, since it's quite similar and required some of the new functions.

**Review by mardelnet — APPROVED** [review]
Looks good to me!

**Pull request merged**
