### PR TITLE
PLANET-2530: Include visual regression tests in the automated testing

### PR DESCRIPTION
**Pull request by pablocubico**
Starting this PR so we can move the conversation here.

I added/updated a few URLs according to the default content, let me know which ones you think we should keep / update / add, etc.

I also added the option to create a CI report, I just wanted to test it as I saw it was present in Nikos's `planet-2530` branch. Do we need it?

### CODE REVIEW

**Comment by pablocubico** [comment]
@comzeradd @27Bslash6 let me know your thoughts!

**Comment by comzeradd** [comment]
Yes, the "CI" option will create a report in junit format, which is what CircleCI wants.

I wouldn't add all the footer links on paths, since all of them use the same template. One should be enough (eg. Copyright).

**Comment by pablocubico** [comment]
Ok! Removed those URLs, I thought about keeping the Privacy and Cookies page since it has a slightly different layout (a "submenu block") that I guess may be affected for other changes. Let me know if you think it's unnecessary, I'll remove it too.

The script currently takes a URL argument, let me know if we should change that to an environment variable or some other method. What else do you  need from me to close this?

**Comment by pablocubico** [comment]
This became outdated and superseded by the `planet-uitests` branch.

**Pull request closed without merging**
