### PR TITLE
PLANET-7527 Move blocks report into master theme

### PR DESCRIPTION
**Pull request by sagarsdeshmukh**
Ref. https://jira.greenpeace.org/browse/PLANET-7527

> Requirements
> 
>     Migrate Blocks Report code to master theme.
>     That should also include classic blocks report functionality.
>     Verify that the API endpoints also work with the plugin de-activated.

The following folder name is changed during the migration to the master theme:
[classes/search](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/tree/main/classes/search) => [src/BlockReportSearch ](https://github.com/greenpeace/planet4-master-theme/tree/PLANET-7527-move-block-report/src/BlockReportSearch)

**Testing:**
- You can test this [PR](https://github.com/greenpeace/planet4-master-theme/pull/2303) along with blocks repo [PR](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/1215) on Local environment or on [test-venus](https://www-dev.greenpeace.org/test-venus/wp-admin/?page=plugin_blocks_report) test instance
- ~~De-activate the Blocks plugin, and check all [blocks reports](https://www-dev.greenpeace.org/test-sinope/wp-admin/?page=plugin_blocks_report), It should work as expected~~ The blocks report functionality should work as as expected
- The Plugins [blocks report API](https://www-dev.greenpeace.org/test-venus/wp-json/plugin_blocks/v3/plugin_blocks_report/) should work as expected.

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [sinope](https://www-dev.greenpeace.org/test-sinope) | [admin](https://www-dev.greenpeace.org/test-sinope/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-sinope/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-sinope) | [composer-local.json](https://github.com/greenpeace/planet4-test-sinope/blob/main/composer-local.json)

:watch: 2024.06.04 06:22:11

**Review by Osong-Michael — COMMENTED** [review]
Hey @sagarsdeshmukh testing this locally we don't seem to have the report for `planet4-block-templates`, was that intentional, because with the old implementation we had that report?

Screenshot 2024-07-03 at 11 25 43

**Comment by sagarsdeshmukh** [comment]
> PLANET-7527 Remove blocks report functionality from blocks plugin greenpeace/planet4-plugin-gutenberg-blocks#1215

Good catch 👍 , It should show block templates as well.

**Comment by sagarsdeshmukh** [comment]
> Hey @sagarsdeshmukh testing this locally we don't seem to have the report for `planet4-block-templates`, was that intentional, because with the old implementation we had that report?
> 
> Screenshot 2024-07-03 at 11 25 43

Hi @Osong-Michael , Could you please check now?

**Comment by Osong-Michael** [comment]
> > Hey @sagarsdeshmukh testing this locally we don't seem to have the report for `planet4-block-templates`, was that intentional, because with the old implementation we had that report?
> > Screenshot 2024-07-03 at 11 25 43
> 
> Hi @Osong-Michael , Could you please check now?

Hey Sagar, just tested now. Still no planet4-block-templates in the report and also something weird on the test-instance. It does not seem to filter by block name

Screenshot 2024-07-11 at 09 54 53
Screenshot 2024-07-11 at 09 56 04

**Comment by sagarsdeshmukh** [comment]
> > > Hey @sagarsdeshmukh testing this locally we don't seem to have the report for `planet4-block-templates`, was that intentional, because with the old implementation we had that report?
> > > Screenshot 2024-07-03 at 11 25 43
> > 
> > 
> > Hi @Osong-Michael , Could you please check now?
> 
> Hey Sagar, just tested now. Still no `planet4-block-templates` in the report and also something weird on the test-instance. It does not seem to filter by block name
> 
> Screenshot 2024-07-11 at 09 54 53 Screenshot 2024-07-11 at 09 56 04

Hi @Osong-Michael , As discussed on DM, if the blocks plugin is deactivated the block template list will not show in dropdown(cause the blocks template white listing logic is still in blocks plugin)

**Review by Osong-Michael — APPROVED** [review]
Looks good to me 👍

**Review by GP-Dan-Tovbein — APPROVED** [review]
Code looks good to me! 👏 great job!

**Review by mleray — APPROVED** [review]
Tested on the instance, looks good to me 👍

**Pull request merged**
