### PR TITLE
PLANET-6902: Site name appears twice in html title tag

### PR DESCRIPTION
**Pull request by lithrel**
Ref: https://jira.greenpeace.org/browse/PLANET-6902
Since: https://github.com/greenpeace/planet4-master-theme/pull/1780

> Site title (ie "Greenpeace International") appears twice in the site <title> tag.

- Making sure that the site title is generated the same way for `<title>` tag and `<meta>` tags
- Site name is appended to title in templates only

## Test

The Opengraph title field is at the bottom of the page in the editor, in "Open graph / Social fields".
Check title tag and meta tags `title`, `og:title`, and `twitter:title` on the frontend for:
- Page without Opengraph title
- Page with Opengraph title different than the Page title

### CODE REVIEW

**Review by GP-Dan-Tovbein — COMMENTED** [review]
I've tested on my local and the only "issue" that I see is that special characters are parsed to html characters code.

For example
```
<title>Nature - Greenpeace</title>
```
to
```
<meta property="og:title" content="Nature&#x20;-&#x20;Greenpeace" />
<meta name="twitter:title" content="Nature&#x20;-&#x20;Greenpeace">
```

Is that ok?

**Comment by lithrel** [comment]
> Is that ok?

I think so yes, it's already the case at the moment in production, it's done by a function to escape text for HTML attributes.
But I have [some tests failing](https://app.circleci.com/pipelines/github/greenpeace/planet4-master-theme/6193/workflows/192e0d4f-f652-4cd0-928c-06323918353d/jobs/39576/steps), I need to fix that before review/merge :grimacing:

**Comment by lithrel** [comment]
@GP-Dan-Tovbein  I found the issue on tests (Timber cache issue mostly), it should work now and good for review :)

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [oberon](https://www-dev.greenpeace.org/test-oberon) | [admin](https://www-dev.greenpeace.org/test-oberon/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-oberon/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-oberon) | [composer-local.json](https://github.com/greenpeace/planet4-test-oberon/blob/main/composer-local.json)

:watch: 2022.09.08 12:36:48

**Review by GP-Dan-Tovbein — APPROVED** [review]
Code looks good to me!

**Pull request merged**
