### PR TITLE
PLANET-7275 Update login button color to reflect new visual identity

### PR DESCRIPTION
**Pull request by mleray**
### Description

See [PLANET-7275](https://jira.greenpeace.org/browse/PLANET-7275)

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [saturn](https://www-dev.greenpeace.org/test-saturn) | [admin](https://www-dev.greenpeace.org/test-saturn/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-saturn/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-saturn) | [composer-local.json](https://github.com/greenpeace/planet4-test-saturn/blob/main/composer-local.json)

:watch: 2023.11.16 10:45:28

**Review by lithrel — APPROVED** [review]
:+1: 
We could also edit font-family/weight to completely follow our design ?

**Comment by mleray** [comment]
> 👍 We could also edit font-family/weight to completely follow our design ?

Yeah I thought about that @lithrel, we could change the font weight for sure but I'm not sure about the font family, I don't think our Greenpeace fonts are available there 🤔

**Comment by lithrel** [comment]
I guess we could enqueue more css stuff in `MasterSite::add_login_stylesheet()`, but it's also fine like that :)

**Review by lithrel — APPROVED** [review]
:+1:

**Pull request merged**
