### PR TITLE
PLANET4-2347 Imagestest

### PR DESCRIPTION
**Pull request by angtheod**
https://greenpeace.github.io/planet4-imagestest-results/

The solution applied in the 6th image produces much better quality than P4 currently produces
and at the same time -47% size on retina-large images, -38% size on large images and -17% on medium images (on large and medium images results about the size of the 2 tested images are conflicting though).
```
Resize: Lanczos
Sharpening: unsharpMask( Radius 1, Sigma 0.45, Amount 3, Threshold 0 )
Compression: Interlace_Plane
Quality: 60
```

### CODE REVIEW

**Comment by comzeradd** [comment]
Can you try rebasing against the develop branch? It seems you a lot of merge commits that shouldn't be part of the PR.

**Comment by angtheod** [comment]
@comzeradd Rebasing You could Rebase and Merge via Github but it will not delete the merge commits. If we want these to be removed I would need to create a new branch and either cherry-pick the commits or create new commits with the same code changes. Do we want this?

**Comment by comzeradd** [comment]
I created a new rebased branch. Can you check that this has all the changes? It has all the commits, without the merge ones.

https://github.com/greenpeace/planet4-master-theme/compare/develop...imagestest-rebased?expand=1

**Comment by angtheod** [comment]
@comzeradd You cherry-picked them?

**Comment by comzeradd** [comment]
@angtheod no, I just did `git rebase develop` from the imagestest branch, and we were lucky enough not to have any conflict :stuck_out_tongue:

**Comment by angtheod** [comment]
@comzeradd This is kind of rewriting history and Linus himself suggests we avoid this on shared repos, but I'm fine with it if everyone else is. We do need though to keep the 'imagestest' as branch name since the https://k8s.p4.greenpeace.org/imagestest website builds on it, so I will update this one if that ok?

**Comment by comzeradd** [comment]
Yes, you can just push force on this branch after you rebase.

Rewriting history is indeed a bad idea. But that refers to shared branches, in our case develop, master. Amending feature branches is quite common during the review process, either through rebasing or squashing commits.

**Pull request closed without merging**
