### PR TITLE
PLANET-7401 Move Page Header block pattern into master theme

### PR DESCRIPTION
**Pull request by sagarsdeshmukh**
Ref. https://jira.greenpeace.org/browse/PLANET-7401

**Testing**
- Create a new page
- Click on "+" and click on "Patterns" tab
- The Page Header block pattern should be visible on that list

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [iocaste](https://www-dev.greenpeace.org/test-iocaste) | [admin](https://www-dev.greenpeace.org/test-iocaste/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-iocaste/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-iocaste) | [composer-local.json](https://github.com/greenpeace/planet4-test-iocaste/blob/main/composer-local.json)

:watch: 2024.06.19 08:23:14

**Review by Osong-Michael — APPROVED** [review]
👍 tested on local, works as expected.

**Comment by GP-Dan-Tovbein** [comment]
Code looks good to me!
However, don't we also need also to remove [this](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/5547b9704a59161c1ada8d19b247fcfd45a492b4/classes/class-loader.php#L174-L177) and all its related style sheets?

**Comment by sagarsdeshmukh** [comment]
> Code looks good to me! However, don't we also need also to remove [this](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/blob/5547b9704a59161c1ada8d19b247fcfd45a492b4/classes/class-loader.php#L174-L177) and all its related style sheets?

Hi Dan, Yes, surely. I have updated both PRs. Could you please recheck?

**Review by GP-Dan-Tovbein — APPROVED** [review]
Code looks good to me! 
Thinking loud.. don't we need to add also the Page Header block stylesheets?

**Comment by sagarsdeshmukh** [comment]
> Code looks good to me! Thinking loud.. don't we need to add also the Page Header block stylesheets?

You are right, I added the PageHeader.scss in master theme.

**Pull request merged**
