### PR TITLE
Add id for page-content and post-content

### PR DESCRIPTION
**Pull request by Osong-Michael**
Added `id="content"` for post and page content

### CODE REVIEW

**Comment by mleray** [comment]
@comzeradd the `evergreen.twig` template also has the `page-content` class, but do we need to update it? Is it still used?

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [janus](https://www-dev.greenpeace.org/test-janus) | [admin](https://www-dev.greenpeace.org/test-janus/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-janus/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-janus) | [composer-local.json](https://github.com/greenpeace/planet4-test-janus/blob/main/composer-local.json)

:watch: 2024.04.23 11:28:56

**Comment by comzeradd** [comment]
> @comzeradd the `evergreen.twig` template also has the `page-content` class, but do we need to update it? Is it still used?

Yes, I think it’s still being used in certain pages.

**Review by mleray — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
