### PR TITLE
Make sure unit tests run on the right WP version

### PR DESCRIPTION
**Pull request by comzeradd**
Just the counterpart of https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/pull/719

### CODE REVIEW

**Comment by planet-4** [comment]
### Test instance is ready :rocket:

:new_moon: [pandora](https://www-dev.greenpeace.org/test-pandora) | [admin](https://www-dev.greenpeace.org/test-pandora/wp-admin/) | [blocks report](https://www-dev.greenpeace.org/test-pandora/wp-admin/?page=plugin_blocks_report) | [CircleCI](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora) | [composer-local.json](https://github.com/greenpeace/planet4-test-pandora/blob/main/composer-local.json)

:watch: 2021.11.12 12:57:24

**Comment by sagarsdeshmukh** [comment]
The phpunit 7.5.* needs to add a name attribute to `<testsuite>` element.
```
PHPUnit 7.5.20 by Sebastian Bergmann and contributors.

  Warning - The configuration file did not pass validation!
  The following problems have been detected:

  Line 11:
  - Element 'testsuite': The attribute 'name' is required but missing.
```
ref. https://phpunit.readthedocs.io/en/9.5/configuration.html#the-testsuites-element

**Comment by comzeradd** [comment]
> The phpunit 7.5.* needs to add a name attribute to `<testsuite>` element.

Good catch! Commit amended.

**Review by sagarsdeshmukh — APPROVED** [review]
👍

**Pull request merged**
