### PR TITLE
PLANET-5983: Move in styleguide

### PR DESCRIPTION
**Pull request by Inwerpsel**
Ref: https://jira.greenpeace.org/browse/PLANET-5983

---

This should move in the entire styleguide repo (except parts only relevant to the styleguide repo itself). It's moved to the location it already was in the theme.

Other repos that used the styleguide can be switched to use master theme as a submodule instead after this PR is merged.

I also needed to fix some code style issues in the styleguide, and also one in master theme before I could make the test pass. These are the commits starting from https://github.com/greenpeace/planet4-master-theme/pull/1344/commits/b489975a0008c90871f8562c92212a891a63b987

### CODE REVIEW

**Review by lithrel — APPROVED** [review]
:+1: LGTM
Confused about testing ? me too, couldn't `git checkout` it (something about not wanting to overwrite untracked files), but `git switch -f move-in-styleguide` worked :)

**Comment by Inwerpsel** [comment]
>  LGTM
> Confused about testing ? me too, couldn't `git checkout` it (something about not wanting to overwrite untracked files), but `git switch -f move-in-styleguide` worked :)

Yes it's not straightforward, especially when moving the submodules in the other sites. I don't know if checking out directly would work, since I only went to this branch by actually changing the needed things one by one. Not sure what happens when switching back and forth. I'll maybe try after I'm done with the other PR repos. Unless we merge this already, then I never need to know :smile:

**Comment by lithrel** [comment]
Just a few diffs that I see between theme and plugin styleguide code, not sure where it comes from I'll just paste it here :+1: 

```
diff -r theme/assets/src/scss/styleguide/ plugin/assets/src/styles/styleguide/
diff --color -r theme/assets/src/scss/styleguide/.git plugin/assets/src/styles/styleguide/.git
1c1
< gitdir: ../../../../.git/modules/assets/src/scss/styleguide
---
> gitdir: ../../../../.git/modules/assets/src/styles/styleguide
diff --color -r theme/assets/src/scss/styleguide/src/base/_mixins.scss plugin/assets/src/styles/styleguide/src/base/_mixins.scss
189a190,191
>     -webkit-transform: skew($deg);
>     -ms-transform: skew($deg);
diff --color -r theme/assets/src/scss/styleguide/src/layout/_forms.scss plugin/assets/src/styles/styleguide/src/layout/_forms.scss
68a69,72
>         -moz-transform: rotate(-45deg) scale(-1, 1);
>         -webkit-transform: rotate(-45deg) scale(-1, 1);
>         -o-transform: rotate(-45deg) scale(-1, 1);
>         -ms-transform: rotate(-45deg) scale(-1, 1);
diff --color -r theme/assets/src/scss/styleguide/src/layout/_navbar.scss plugin/assets/src/styles/styleguide/src/layout/_navbar.scss
297a298
>     -webkit-border-radius: 5px;
302a304
>     -webkit-border-radius: 5px;
diff --color -r theme/assets/src/scss/styleguide/src/layout/_skewed-overlay.scss plugin/assets/src/styles/styleguide/src/layout/_skewed-overlay.scss
9a10
>   -webkit-mask-image: linear-gradient(170deg, rgba(0, 0, 0, 1), rgba(0, 0, 0, 1), rgba(226, 119, 119, 0.2), rgba(0, 0, 0, 0));

```

**Comment by Inwerpsel** [comment]
> Just a few diffs that I see between theme and plugin styleguide code, not sure where it comes from I'll just paste it here :
> 
> ```diff
> diff -r theme/assets/src/scss/styleguide/ plugin/assets/src/styles/styleguide/
> diff --color -r theme/assets/src/scss/styleguide/.git plugin/assets/src/styles/styleguide/.git
> 1c1
> < gitdir: ../../../../.git/modules/assets/src/scss/styleguide
> ---
> > gitdir: ../../../../.git/modules/assets/src/styles/styleguide
> diff --color -r theme/assets/src/scss/styleguide/src/base/_mixins.scss plugin/assets/src/styles/styleguide/src/base/_mixins.scss
> 189a190,191
> >     -webkit-transform: skew($deg);
> >     -ms-transform: skew($deg);
> diff --color -r theme/assets/src/scss/styleguide/src/layout/_forms.scss plugin/assets/src/styles/styleguide/src/layout/_forms.scss
> 68a69,72
> >         -moz-transform: rotate(-45deg) scale(-1, 1);
> >         -webkit-transform: rotate(-45deg) scale(-1, 1);
> >         -o-transform: rotate(-45deg) scale(-1, 1);
> >         -ms-transform: rotate(-45deg) scale(-1, 1);
> diff --color -r theme/assets/src/scss/styleguide/src/layout/_navbar.scss plugin/assets/src/styles/styleguide/src/layout/_navbar.scss
> 297a298
> >     -webkit-border-radius: 5px;
> 302a304
> >     -webkit-border-radius: 5px;
> diff --color -r theme/assets/src/scss/styleguide/src/layout/_skewed-overlay.scss plugin/assets/src/styles/styleguide/src/layout/_skewed-overlay.scss
> 9a10
> >   -webkit-mask-image: linear-gradient(170deg, rgba(0, 0, 0, 1), rgba(0, 0, 0, 1), rgba(226, 119, 119, 0.2), rgba(0, 0, 0, 0));
> ```

It's because I temporarily put my branch's last commit on there instead of master. And I needed to fix the CS to make the test pass (removing these vendor prefixes). :+1:

**Comment by Inwerpsel** [comment]
> > Just a few diffs that I see between theme and plugin styleguide code, not sure where it comes from I'll just paste it here :
> > ```diff
> > diff -r theme/assets/src/scss/styleguide/ plugin/assets/src/styles/styleguide/
> > diff --color -r theme/assets/src/scss/styleguide/.git plugin/assets/src/styles/styleguide/.git
> > 1c1
> > < gitdir: ../../../../.git/modules/assets/src/scss/styleguide
> > ---
> > > gitdir: ../../../../.git/modules/assets/src/styles/styleguide
> > diff --color -r theme/assets/src/scss/styleguide/src/base/_mixins.scss plugin/assets/src/styles/styleguide/src/base/_mixins.scss
> > 189a190,191
> > >     -webkit-transform: skew($deg);
> > >     -ms-transform: skew($deg);
> > diff --color -r theme/assets/src/scss/styleguide/src/layout/_forms.scss plugin/assets/src/styles/styleguide/src/layout/_forms.scss
> > 68a69,72
> > >         -moz-transform: rotate(-45deg) scale(-1, 1);
> > >         -webkit-transform: rotate(-45deg) scale(-1, 1);
> > >         -o-transform: rotate(-45deg) scale(-1, 1);
> > >         -ms-transform: rotate(-45deg) scale(-1, 1);
> > diff --color -r theme/assets/src/scss/styleguide/src/layout/_navbar.scss plugin/assets/src/styles/styleguide/src/layout/_navbar.scss
> > 297a298
> > >     -webkit-border-radius: 5px;
> > 302a304
> > >     -webkit-border-radius: 5px;
> > diff --color -r theme/assets/src/scss/styleguide/src/layout/_skewed-overlay.scss plugin/assets/src/styles/styleguide/src/layout/_skewed-overlay.scss
> > 9a10
> > >   -webkit-mask-image: linear-gradient(170deg, rgba(0, 0, 0, 1), rgba(0, 0, 0, 1), rgba(226, 119, 119, 0.2), rgba(0, 0, 0, 0));
> > ```
> 
> It's because I temporarily put my branch's last commit on there instead of master. And I needed to fix the CS to make the test pass (removing these vendor prefixes).  I'll rebase once that's merged.

I was mixing up PRs :see_no_evil: Forgot all parts except "I needed to fix the CS to make the test pass (removing these vendor prefixes)"

**Pull request merged**
